import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

//This is done beacuse of the dynamic component <Button> in SideNavbar
//SSR is causes a hydration error
import dynamic from 'next/dynamic';
const SideNavbar = dynamic(() => import('@/components/SideNavbar'), { ssr: false })

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen w-full bg-white text-black flex",inter.className,{
        'debug-screens': process.env.NODE_ENV === "development"     //this will add the size of screen at bottom of screen but only during development not deployment
        })}>
          {/* sidebar */}
          {/* <p className="border">Sidebar</p> */}
          <SideNavbar />
          {/* mainpage */}
          <div className="p-8 w-full">{children}</div>
          </body>
    </html>
  );
}
